### PR TITLE
Add Experience nginx config

### PR DESCRIPTION
**Pull request by kenoir**
Build a new nginx container for wc.org using variable substitution like all other projects.

### CODE REVIEW

**Comment by kenoir** [comment]
Part of https://github.com/wellcomecollection/wellcomecollection.org/pull/5154/files

**Comment by kenoir** [comment]
I'm not at all sure this is the best way to do nginx config - but it's less confusing for me if they all work the same way and I can see them all in the same place.

**Comment by alexwlchan** [comment]
> I'm not at all sure this is the best way to do nginx config - but it's less confusing for me if they all work the same way and I can see them all in the same place.

At some point it would be good to remind myself: what do we get by putting nginx in front of our apps?

**Comment by jamesgorrie** [comment]
@alexwlchan in this instance you get to put the webapp specific headers and control HTTP here rather than in the app, which is nice.

**Comment by kenoir** [comment]
> > I'm not at all sure this is the best way to do nginx config - but it's less confusing for me if they all work the same way and I can see them all in the same place.
> 
> At some point it would be good to remind myself: what do we get by putting nginx in front of our apps?

Only services with APIs have nginx and if you look in the nginx configs, there are a few things (CORS, compression, redirection with API Gateway things) - extracting those from the applications makes the services simpler and having a standard pattern for types of app makes them more understandable.

**Pull request merged**
